apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  labels:
    app: hello-go
    bcpxpress.yourco.io/itsi: "ITSI-12345"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
        - name: hello-go
          image: ghcr.io/sdiazben/hello-go:ea8c534489b3afa19b2c5f3852c9d917d3a9ab02
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "demo"
            - name: TEAM
              value: "platform"
