apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  labels:
    app: hello-go
    bcpxpress.yourco.io/itsi: "ITSI-12345"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
        - name: hello-go
          image: ghcr.io/sdiazben/hello-go:89cf3e0f7ead6cc525d16ffe8620c5bc68678e31
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: "demo"
            - name: TEAM
              value: "platform"
